name: Limited CI on H100

on:
  pull_request:
    paths:
      - .github/workflows/test-h100.yml
  workflow_dispatch:
  schedule:
    - cron: 0 4,10,16,22 * * *  # every 6 hours
  push:
    tags:
      - ciflow/h100/*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:

  get-label-type:
    if: github.repository_owner == 'pytorch'
    name: get-label-type
    uses: pytorch/pytorch/.github/workflows/_runner-determinator.yml@main
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}

  linux-focal-cuda12_6-py3_10-gcc11-sm90-build:
    name: linux-focal-cuda12.6-py3.10-gcc11-sm90
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      runner_prefix: "${{ needs.get-label-type.outputs.label-type }}"
      runner: "linux.12xlarge"
      build-environment: linux-focal-cuda12.6-py3.10-gcc11-sm90
      docker-image-name: ci-image:pytorch-linux-focal-cuda12.6-cudnn9-py3-gcc11
      cuda-arch-list: '9.0'
      test-matrix: |
        { include: [
          { config: "smoke", shard: 1, num_shards: 1, runner: "linux.aws.h100" },
        ]}
    secrets: inherit

  linux-focal-cuda12_6-py3_10-gcc11-sm90-test:
    name: linux-focal-cuda12.6-py3.10-gcc11-sm90
    uses: ./.github/workflows/_linux-test.yml
    needs:
      - linux-focal-cuda12_6-py3_10-gcc11-sm90-build
    with:
      build-environment: linux-focal-cuda12.6-py3.10-gcc11-sm90
      docker-image: ${{ needs.linux-focal-cuda12_6-py3_10-gcc11-sm90-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-cuda12_6-py3_10-gcc11-sm90-build.outputs.test-matrix }}
    secrets: inherit
